---
title: Grading Contract
date: "`r format(Sys.time(), '%B %d %Y')`"
output: github_document
params:
  weekonemonday: "2023-01-09"
  thesisdeadline: "2023-01-10"
  springbreak: "2023-01-10"
  name: Tukey Cat
  labs: 11
  portfolios: 10
  grade:
    label: Grade
    value: A
    input: select
    choices:
    - A
    - B
    - Pass
  startweek:
    label: Weekly Due Date
    value: Friday
    input: select
    choices:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
---

```{r setup, include=FALSE}

library(tidyverse)

# R Syllabus Scheduler


advdate <- function(weekonemonday,
                    week,
                    topic =  NULL,
                    assignment = NULL,
                    unit = "Module ") {
  # as.Date does not like piping
  tmon <- as.Date(weekonemonday + 7 * (week - 1)) %>% 
    format(format = "%m/%d")
  ttue <- as.Date(weekonemonday + 1 + 7 * (week - 1)) %>%
    format(format = "%m/%d")
  twed <- as.Date(weekonemonday + 2 + 7 * (week - 1)) %>%
    format(format = "%m/%d")
  tthu <- as.Date(weekonemonday + 3 + 7 * (week - 1)) %>%
    format(format = "%m/%d")
  tfri <- as.Date(weekonemonday + 4 + 7 * (week - 1)) %>%
    format(format = "%m/%d")
  tsat <- as.Date(weekonemonday + 5 + 7 * (week - 1)) %>%
    format(format = "%m/%d")
  tsun <- as.Date(weekonemonday + 6 + 7 * (week - 1)) %>%
    format(format = "%m/%d")
  zadv <- sprintf("%02d", week)
  
  
  if (is.null(topic) & is.null(assignment)) {
    tmp <- paste0(unit, zadv, ", ", tmon, " - ", tfri)
  } else if (!is.null(assignment)) {
    if (assignment %in%
        c("Friday",
          "friday",
          "f",
          "fri",
          "FRI")) {
      tmp <- paste0(tfri)
    } else if (assignment %in%
               c("thursday",
                 "Thursday",
                 "thurs",
                 "r",
                 "R")) {
      tmp <- paste0(tthu)
    } else if (assignment %in%
               c("wednesday",
                 "Wednesday",
                 "w",
                 "wed",
                 "W")) {
      tmp <- paste0(twed)
    } else if (assignment %in%
               c("Tuesday",
                 "tues",
                 "t",
                 "Tue")) {
      tmp <- paste0(ttue)
    } else if (assignment %in%
               c("monday",
                 "Monday",
                 "m",
                 "mon")) {
      tmp <- paste0(tmon)
    }
  } else{
    tmp <- paste0(unit, zadv, ", ", tmon, " - ", tfri, " : ", topic[week])
  }
  return(tmp)
}

#if(TRUE){
#  
#  dayone <- as.Date("2022-01-10")
#  startweek <- "Friday"
#} else {

dayone <- as.Date(params$weekonemonday)
startweek <- params$startweek


  
#}



topic = c(
  "What is Data Science and Meet the Toolkit",
  "Data and Visualization",
  "Grammar of data wrangling",
  "Data types and Data Transformations",
  "Tips for effective data visualization",
  "Scientific studies and confounding",
  #  "Spring Break",#  "",
  "Web scraping",
  "Functions",
  "Data and Ethics",
  "Fitting and interpreting models",
  "Prediction and overfitting",
  "Cross validation",
  "Quantifying uncertainty",
  "Interactive web apps",
  "Special Topics"
)

```

<!-- This contract is adapted from Annie Somerville's contract https://github.com/anniehsom -->



# Contract Grades – “`r params$grade`” Contract

I, `r params$name`, agree to :

1) Earn “Satisfactory” on `r params$labs` self-paced lab assignments on the schedule specified below.
	-  Satisfactory defined:
  	-  I have attempted all steps of the assignment. If unable to complete steps due to unresolved questions, I have asked questions in Github FAQs or zoom help session, or I have Googled the issue and shown effort to resolve questions;
  	-  I have checked that forked files, repos, or projects appear on my Github account and are accessible;
  	-  I feel like I have spent an adequate amount of time and energy on assignments; 
  	-  My presentation is professional, engaging, and accessible.
2) Produce at least `r params$portfolios` “Satisfactory” portfolio pieces on the schedule specified below.
3) Complete a “Satisfactory” presentation based on some portfolio pieces. 10 minutes total in length.



## SCHEDULE

Note: This is an example schedule. You are welcomed and encouraged to rearrange these labs and events to fit your needs.

- [ ] `r advdate(dayone, 1, topic)`
  - Finish Lab 1 by `r startweek`:  `r advdate(dayone, 1, assignment=startweek)`
- [ ] `r advdate(dayone, 2, topic)`
  - Finish Lab 2 by `r startweek`:  `r advdate(dayone, 2, assignment=startweek)`
  - Propose your contract to Mason by `r startweek`:  `r advdate(dayone, 2, assignment=startweek)`
- [ ]  `r advdate(dayone, 3, topic)`
  - Finish Lab 3  by `r startweek`:  `r advdate(dayone, 3, assignment=startweek)`
  - Finish portfolio piece 1 by `r startweek`:  `r advdate(dayone, 3, assignment=startweek)`
- [ ] `r advdate(dayone, 4, topic)`
  - Finish Lab 4  by `r startweek`:  `r advdate(dayone, 4, assignment=startweek)`
- [ ] `r advdate(dayone, 5, topic)`
  - Finish Lab 5  by `r startweek`:  `r advdate(dayone, 5, assignment=startweek)`
  - Finish portfolio piece 2 by `r startweek`:  `r advdate(dayone, 5, assignment=startweek)`
- [ ] `r advdate(dayone, 6, topic)`
  - Finish Lab 6 by `r startweek`:  `r advdate(dayone, 6, assignment=startweek)`
  - Schedule a check-in with Mason by `r startweek`:  `r advdate(dayone, 6, assignment=startweek)`
- [ ] `r advdate(dayone, 7, topic)`
  - Finish Lab 7 by `r startweek`:  `r advdate(dayone, 7, assignment=startweek)`
  - Finish portfolio piece 3 by `r startweek`:  `r advdate(dayone, 7, assignment=startweek)`
- [ ] `r advdate(dayone, 8, topic)`
  - Finish Lab 8 by `r startweek`:  `r advdate(dayone, 8, assignment=startweek)`
- [ ] `r advdate(dayone, 9, topic)`
  - Finish Lab 9 by `r startweek`:  `r advdate(dayone, 9, assignment=startweek)`
  - Finish portfolio piece 4 by `r startweek`:  `r advdate(dayone, 9, assignment=startweek)`
- [ ] `r advdate(dayone, 10, topic)`
  - Finish Lab 10 by `r startweek`:  `r advdate(dayone, 10, assignment=startweek)`
- [ ] `r advdate(dayone, 11, topic)`
  `r if(params$labs>=11) paste0(" - Finish Lab 11 by ",startweek,": ",advdate(dayone, 11, assignment=startweek))`
  - Finish portfolio piece 5 by `r startweek`:  `r advdate(dayone, 11, assignment=startweek)`
- [ ] `r advdate(dayone, 12, topic)`
  `r if(params$labs>=12) paste0(" - Finish Lab 12 by ",startweek,": ",advdate(dayone, 12, assignment=startweek))`
  - Finish portfolio piece 6 by `r startweek`:  `r advdate(dayone, 12, assignment=startweek)`
- [ ] `r advdate(dayone, 13, topic)`
  `r if(params$labs>=13) paste0(" - Finish Lab 13 by ",startweek,": ",advdate(dayone, 13, assignment=startweek))`
  - Finish portfolio pieces 7 and 8 by `r startweek`:  `r advdate(dayone, 13, assignment=startweek)`
- [ ] `r advdate(dayone, 14, topic)`
  - Finish portfolio piece 9 by `r startweek`:  `r advdate(dayone, 14, assignment=startweek)`
- [ ] `r advdate(dayone, 15, topic)`
  - Finish portfolio piece 10 by `r startweek`:  `r advdate(dayone, 15, assignment=startweek)`
- [ ] Portfolio completion and end-of-semester presentation
  - Due on `r startweek`: `r advdate(dayone, 15, assignment=startweek)`

